language: node_js
node_js:
  - 'lts/boron'   #6.x  - Maintenance LTS
  - 'lts/carbon'  #8.x  - Maintenance LTS
  - 'lts/dubnium' #10.x - Active LTS
  - 'stable'      #11.x - Current Release
before_install:
  - npm i -g npm@^6
install:
  - npm ci
  - npm i g --save-dev codecov
script:
  - npm run build
  - npm t
  - codecov
